### ISSUE TITLE
Bug 02

### ISSUE THREAD

**Issue by rushiranade** [rushiranade/Notes#2]
Duplicate File name.
When someone uses the same heading, the note file gets replaced.
I guess if we don't allow same heading by checking filename, and set an error it will get fixed.
@RR192007 doing this

**Comment by rushiranade** [comment]
@RR192007 not able to fix

**Comment by RR192007** [comment]
@rushiranade - not getting fixed. I added a note on top of the screen - "Notes with the same heading will be replaced"

Regards,
@RR192007
